### ISSUE TITLE
Piped text is being highlighted

### ISSUE THREAD

**Issue by jameskolce** [hlissner/emacs-pug-mode#11]
![image](https://cloud.githubusercontent.com/assets/2559808/21077955/e6915ba2-bf19-11e6-8e96-bbcaba97e40a.png)

I'll check this out too.

**Comment by jameskolce** [comment]
I have fixed this, will send a pull request soon.

**Comment by hlissner** [comment]
This was intentional, to distinguish plain-text from normal text, but I don't mind removing it.

Also to prevent tag names being highlighted in plain-text. For instance, try:

```jade
h1
  strong My name is ...
  | p diddy
```

Without the piped highlight, the `p` is highlighted as a tag. Does that happen with your solution?

**Comment by jameskolce** [comment]
Yeah, I thought it was intentional because I read this in the readme last night:

> …it has poor/no fontification of plain-text…

But I think the content of elements shouldn't have any style because it can be anything. Some parts were marked as strings, but things should be considered strings only when they are in `""` or `''`.

For example, we can have this:

```Jade
.myelement Text with <em>HTML</em> on it.
| and a <a href='#'>Link</a>.
```

In that case, the content of `.myElement` isn't strictly a string but HTML.

My changes look like this right now:

![image](https://cloud.githubusercontent.com/assets/2559808/21116505/13b55840-c073-11e6-9345-0552739631dd.png)

Now the `include`and `extends` statements are highlighted equally. The tag interpolation only highlights the tag name. The `|` is marked in the same style as the tag, so the connection between the two is evident. If there is a tag next to the pipe, it doesn't get highlighted

I still would like to give a different color to the symbols `#[ … ]`, `#{ … }` and `!{ … }`, especially for the final delimiter, so is clear that they are not part of the content. I tried to do it but it wasn't taking effect, I guess something else is overriding that so I think I will do it after making a clean up of all the font-locks. And because I'll be doing several changes, I wanted to mention that you are not obligated to merge changes if you don't like something, I can keep a fork instead so everybody is happy :) though I think having just one mode for pug would be optimal, but is okay.

**Comment by hlissner** [comment]
That makes sense. I definitely welcome these changes. I haven't had much time to look into pug-mode myself lately, so you've been a tremendous help! Thank you by the way!

**Comment by jameskolce** [comment]
Sure, no problem! I'm glad the changes are welcome!

**Comment by jameskolce** [comment]
By the way, I'll be adding issues in this repo to keep track of things, I'll fix them from time to time.

**Comment by hlissner** [comment]
I trust this issue has been resolved by your PRs, so I'll close this thread. Feel free to reopen otherwise.
