### ISSUE TITLE
Problem with interpolated tags and attributes

### ISSUE THREAD

**Issue by jameskolce** [hlissner/emacs-pug-mode#12]
![image](https://cloud.githubusercontent.com/assets/2559808/21119868/c3e5bf1c-c081-11e6-88e3-3bc24a6f6bf9.png)

All the text next to the interpolation gets highlighted when used with attributes.

**Comment by jameskolce** [comment]
![image](https://cloud.githubusercontent.com/assets/2559808/21163601/5d3dfbbe-c151-11e6-997b-b8a2972d22d1.png)

**Comment by hlissner** [comment]
Not a definitive solution, but I've disabled attribute highlighting for now. I'll write a proper parser for this whenever I get around to it.
