### ISSUE TITLE
"+" Key is working as TAB for indentation but also adds the "+" sign

### ISSUE THREAD

**Issue by jameskolce** [hlissner/emacs-pug-mode#15]

**Comment by bargeruns** [comment]
Experiencing the same issue. Entering a "+" char is interpreted as SHIFT+TAB, and inserts the character but also outdents the current line.

**Comment by hlissner** [comment]
This was due to `electric-indent-mode`. `+` was an electric character for pug-mode, but I've removed it, so this should be fixed. Feel free to reopen this otherwise.
