### ISSUE TITLE
Comments are not highlighted as comments.

### ISSUE THREAD

**Issue by terrycloth** [hlissner/emacs-pug-mode#19]
Neither buffered (`//`) nor unbuffered (`//-`) comments are highlighted. I have a face for comments set via Emacs Customizer, which makes it so comments in files normally appear as bold white, but in pug files, comments seem to render as plain text.

```elisp
(custom-set-faces
  '(font-lock-comment-face ((t (:background "Transparent" :foreground "White" :weight bold))))
  ;; and other faces...
)
```

If the comment includes a colon, the word after it is highlighted as if it were a tag.

![screenshot from 2017-09-11 21-15-04](https://user-images.githubusercontent.com/3881885/30307875-5b85b79c-9736-11e7-90fa-f91a730d3019.png)

#### System Info :computer:

- OS: Fedora 26 Workstation x86_64 (gnu/linux)
- Emacs: 25.2.1, both in an X window or in GNOME Terminal 3.24
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Distribution: spacemacs
- pug-mode 20170127.1949 (installed from MELPA)
- Editing style: vim
- Completion: helm
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

**Comment by hlissner** [comment]
I'm unable to recreate this. Do you see fontification errors in *Messages*? (See `M-x view-echo-area-messages`). And could you offer a screenshot with more context? It's possible a parsing error occurring elsewhere could be causing this.

**Comment by terrycloth** [comment]
The `*Messages*` buffer shows no errors after launching Spacemacs and opening a .pug file.

> It's possible a parsing error occurring elsewhere could be causing this.

Hmm, I think you might be right. After playing around with placement of comments, I noticed that comments are highlighted when they are not indented, or if they are indented with spaces, but they're _not_ highlighted when indented with tabs.

**Comment by hlissner** [comment]
Ah, that's it. I completely overlooked tabs for indentation. I've adjusted the syntax highlighter to take tabs into account which should fix your issue. Let me know if it doesn't!

**Comment by terrycloth** [comment]
Okay, tab-indented comments all seem to be highlighted now, thanks.

One remaining problem, which seems related enough to add on here: round, square, and curly brackets, and double quotes are highlighted inside of comments. Is there a reason for this? From using other editors, I would normally expect comment highlighting to ignore all syntax elements, except maybe for the todo and warning keywords `TODO:`, `FIXME:`, `NOTE:` and so on.

![screenshot from 2017-09-13 18-00-26](https://user-images.githubusercontent.com/3881885/30407533-87eee308-98ad-11e7-888d-09186c17011d.png)

**Comment by hlissner** [comment]
Alright, that last commit should fix the issue with strings and brackets in comments. Let me know if it doesn't!

**Comment by terrycloth** [comment]
I tested again with the latest MELPA release in a clean Emacs configuration, and the issue is now resolved.

Thanks for all your hard work!
