### ISSUE TITLE
Elements or classes after first element stop being highlighted if there is a space somewhere

### ISSUE THREAD

**Issue by vladh** [hlissner/emacs-pug-mode#2]
![](http://i.imgur.com/5NPtNpN.png)

Here, I would expect `div.test` to be highlighted even if ` hello` follows it. Also, inline nested tags aren't highlighted — I would expect the `span` in `span hi` to be highlighted even if it's inside a `div`.

I would submit a pull request, but I'm afraid I'm not sure how to fix these.

Thank you for `pug-mode`!

**Comment by hlissner** [comment]
Thanks for the report! I've refactored pug-font-lock-keywords, and it _seems_ to work fine (I say seems because I wasn't specifically targeting this problem):

![](http://i.cubeupload.com/CA2caJ.png)

Please update and let me know if it was fixed.

**Comment by vladh** [comment]
Wow, fastest fix ever! Thank you, it does work fine. Amusingly, inline tags are now highlighted in one color, and the first letter of their content another. I guess inline tags aren't a big deal anyway though. I'll leave this issue open for now, just so that there's a record of the inline thing.

Sidenote: what theme are you using?

**Comment by hlissner** [comment]
I have some improvements for pug-mode's syntax highlighting on the horizon that should fix these issues, but there's some refactoring to do first.

As for the theme, I'm using something homebrewed, inspired by Atom's Dark One: https://github.com/hlissner/emacs-doom-theme

**Comment by hlissner** [comment]
I've pushed a [hopeful] fix for your issue. Let me know if it persists!

**Comment by vladh** [comment]
Looks like this:

![](http://i.imgur.com/Y0F6sGR.png)

**Comment by hlissner** [comment]
Oh wow. And this is with the update?

**Comment by vladh** [comment]
I mean, I think so, I nuked `~/.emacs.d/elpa`…

**Comment by hlissner** [comment]
I just checked MELPA; it hasn't updated pulled the update yet. 

It usually takes some time for updates to propagate, so we might have to wait a bit, unless you don't mind downloading [pug-mode.el](https://github.com/hlissner/emacs-pug-mode/blob/master/pug-mode.el) straight.

**Comment by vladh** [comment]
I don't know *what* it was, but it works now!

![](http://i.imgur.com/SvmHbDJ.png)

Thanks for all the work :D

**Comment by hlissner** [comment]
Woohoo! Glad I could help!
