### ISSUE TITLE
Add support for unbuffered comments.

### ISSUE THREAD

**Issue by terrycloth** [hlissner/emacs-pug-mode#20]
Currently, the default is to create "buffered" `//` comments when running either the `pug-comment-block` or `evilnc-comment-operator` commands. It would be nice if there were also a way to create "unbuffered" `//-` comments.

Or, personally, my comments are almost always specific to the Pug templating logic (or `TODO` type of placeholder comments), and almost never really pertinent to the output HTML. So for me, I think it would also be okay, maybe even _better_, if `pug-mode` defaulted to unbuffered `//-` comments _instead_. I guess I have no idea what the worldwide usage rates of the different types of comments are, though.

If you only supported one type, it might also make sense to do unbuffered comments because the included hyphen means the command shortcuts would save users an extra keystroke versus buffered comments.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- pug-mode-20170914.208
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers: `(emacs-lisp html helm javascript markdown shell-scripts vimscript)`
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

**Comment by hlissner** [comment]
It's a good argument. My preference is the same, so I've gone ahead and made unbuffered comments the default. With `pug-comment-block` in particular, you can use the universal argument to reverse this. i.e. `C-u M-x pug-comment-block` will use buffered comments. Commenting plugins (like evil-nerd-commenter and evil-commentary) should respect this change as well. 

Let me know if you find any issues.

**Comment by terrycloth** [comment]
Looks good to me, thanks!
