### ISSUE TITLE
pug-comment-block in visual mode

### ISSUE THREAD

**Issue by terrycloth** [hlissner/emacs-pug-mode#21]
`pug-comment-block` puts the pug markup block currently under the pointer into a comment block. Weird things happen when you try to run this command with lines selected in `evil-visual-mode` and `evil-visual-line-mode`.

It seems Pug Mode calculates the pointer position as being at the end of the selection. So, when I select through the end of the line, to the invisible end-of-line character, the commenting command calculates the pointer position as being at the beginning of the _next_ line. The block comment therefore is put in the first column, and the rest of the entire document is commented.

I have not yet tested in a clean, non-evil Emacs environment.

Seems to me that Pug Mode should do one of these two things:

1. Add support for running the block comment command on a selection, as this is a fairly intuitive thing users might expect to be able to do. Probably all partial and complete blocks within the selection get moved to a block comment?
2. Document the fact that you don't _need_ to make a selection, and in fact probably shouldn't.

**Comment by hlissner** [comment]
Yes, your diagnosis is exactly right. I'll look into adding region support over the weekend.

That said, do you find yourself using it over `evil-nerd-commenter`? I rarely use major mode commenting commands since I find it (or `evil-commentary`) with [evil-indent-plus](https://github.com/TheBB/evil-indent-plus) (for indentation-based text objects) vastly superior.

**Comment by terrycloth** [comment]
No, I also tend to use the normal commenter commands instead, so this isn't a deal-breaker for me. I mostly brought this up because I noticed the issue while testing the fix for #20. As far as I know, the general-purpose commenting packages only support line comments in Pug, though.

**Comment by hlissner** [comment]
Alright, as of https://github.com/hlissner/emacs-pug-mode/commit/20eba8a410f6b13c7e31e0061753422647973ea5 `pug-{,un}comment-block` supports regions. Give it a try and let me know it gives you any trouble.

**Comment by terrycloth** [comment]
(sorry for the delayed response.)

Yup, seems to work great now. Thanks!
