### ISSUE TITLE
License issue: must use the same license as slim-mode

### ISSUE THREAD

**Issue by xuhdev** [hlissner/emacs-pug-mode#24]
As slim-mode uses GPLv3+, plug-mode, as a derived work of slim-mode, is required to use the same license.

**Comment by hlissner** [comment]
Ah, this slipped under my radar. The license [was added several months after pug-mode was born](https://github.com/slim-template/emacs-slim/commit/3636d18ab1c8b316eea71c4732eb44743e2ded87).

I've now changed it to GPLv3. Thanks for letting me know!
