### ISSUE TITLE
Auto-compile html when saving

### ISSUE THREAD

**Issue by molofishy** [hlissner/emacs-pug-mode#3]
I wrote an issue [here](https://github.com/brianc/jade-mode/issues/69). I assume it's relevant for pug-mode too.

**Comment by hlissner** [comment]
Sure thing. I'll see to putting it in.

**Comment by molofishy** [comment]
Thanks!

**Comment by hlissner** [comment]
Yikes, sorry for taking so long (it slipped my mind)!
